# Generated by Django 5.2.15 on 2026-06-13 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WargaProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nik', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True)),
                ('agama', models.CharField(blank=True, max_length=50, null=True)),
                ('status_perkawinan', models.CharField(blank=True, choices=[('belum_kawin', 'Belum Kawin'), ('kawin', 'Kawin'), ('cerai_hidup', 'Cerai Hidup'), ('cerai_mati', 'Cerai Mati')], max_length=20, null=True)),
                ('pendidikan', models.CharField(blank=True, max_length=100, null=True)),
                ('pekerjaan', models.CharField(blank=True, max_length=100, null=True)),
                ('no_kk', models.CharField(blank=True, max_length=16, null=True)),
                ('hubungan_keluarga', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('blok', models.CharField(blank=True, max_length=10, null=True)),
                ('no_rumah', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('tidak_aktif', 'Tidak Aktif'), ('pindah', 'Pindah'), ('meninggal', 'Meninggal')], default='aktif', max_length=20)),
                ('foto', models.FileField(blank=True, null=True, upload_to='foto-profil/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warga_deleted', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'warga_profiles',
                'indexes': [models.Index(fields=['nama_lengkap'], name='idx_warga_nama'), models.Index(fields=['blok'], name='idx_warga_blok'), models.Index(fields=['status'], name='idx_warga_status'), models.Index(fields=['nik'], name='idx_warga_nik'), models.Index(fields=['is_deleted'], name='idx_warga_is_deleted')],
            },
        ),
    ]
