# Generated by Django 5.2.15 on 2026-06-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_wargaprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wargaprofile',
            name='no_kk',
        ),
    ]
