# Generated by Django 5.2.15 on 2026-06-15 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_wargaprofile_no_kk'),
        ('kartu_keluarga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wargaprofile',
            name='kartu_keluarga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anggota', to='kartu_keluarga.kartukeluarga'),
        ),
        migrations.AlterField(
            model_name='wargaprofile',
            name='hubungan_keluarga',
            field=models.CharField(blank=True, choices=[('kepala_keluarga', 'Kepala Keluarga'), ('istri', 'Istri'), ('anak', 'Anak'), ('orang_tua', 'Orang Tua'), ('menantu', 'Menantu'), ('cucu', 'Cucu'), ('saudara', 'Saudara/i'), ('lainnya', 'Lainnya')], max_length=50, null=True),
        ),
    ]
