# Generated by Django 5.2.15 on 2026-06-15 14:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_wargaprofile_no_kk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KartuKeluarga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('no_kk', models.CharField(max_length=16, unique=True)),
                ('alamat', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kk_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kartu_keluarga',
            },
        ),
        migrations.CreateModel(
            name='PengajuanAnggotaBaru',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_anggota', models.JSONField()),
                ('alasan', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=20)),
                ('catatan_admin', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('kartu_keluarga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_tambah', to='kartu_keluarga.kartukeluarga')),
                ('pengaju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_tambah_anggota', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_tambah_anggota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pengajuan_anggota_baru',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PengajuanPenghapusanAnggota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alasan', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=20)),
                ('catatan_admin', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('kartu_keluarga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_hapus', to='kartu_keluarga.kartukeluarga')),
                ('pengaju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_hapus_anggota', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_hapus_anggota', to=settings.AUTH_USER_MODEL)),
                ('warga_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_penghapusan', to='accounts.wargaprofile')),
            ],
            options={
                'db_table': 'pengajuan_penghapusan_anggota',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PengajuanPerubahanWarga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_changes', models.JSONField()),
                ('alasan', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=20)),
                ('catatan_admin', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('pengaju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_ubah_data', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_perubahan_warga', to=settings.AUTH_USER_MODEL)),
                ('warga_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_perubahan', to='accounts.wargaprofile')),
            ],
            options={
                'db_table': 'pengajuan_perubahan_warga',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kartukeluarga',
            index=models.Index(fields=['no_kk'], name='idx_kk_no_kk'),
        ),
        migrations.AddIndex(
            model_name='pengajuananggotabaru',
            index=models.Index(fields=['status'], name='idx_pengajuan_tambah_status'),
        ),
        migrations.AddIndex(
            model_name='pengajuananggotabaru',
            index=models.Index(fields=['kartu_keluarga'], name='idx_pengajuan_tambah_kk'),
        ),
        migrations.AddIndex(
            model_name='pengajuanpenghapusananggota',
            index=models.Index(fields=['status'], name='idx_pengajuan_hapus_status'),
        ),
        migrations.AddIndex(
            model_name='pengajuanpenghapusananggota',
            index=models.Index(fields=['kartu_keluarga'], name='idx_pengajuan_hapus_kk'),
        ),
        migrations.AddIndex(
            model_name='pengajuanperubahanwarga',
            index=models.Index(fields=['status'], name='idx_pengajuan_ubah_status'),
        ),
        migrations.AddIndex(
            model_name='pengajuanperubahanwarga',
            index=models.Index(fields=['warga_target'], name='idx_pengajuan_ubah_target'),
        ),
    ]
