# Generated by Django 5.2.15 on 2026-06-14 14:58

import django.db.models.deletion
import pengaduan.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('kategori', models.CharField(choices=[('infrastruktur', 'Infrastruktur'), ('keamanan', 'Keamanan'), ('kebersihan', 'Kebersihan'), ('sosial', 'Sosial'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20)),
                ('status', models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Diproses'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak')], default='diajukan', max_length=20)),
                ('foto', models.FileField(blank=True, null=True, upload_to=pengaduan.models.pengaduan_foto_upload_path)),
                ('status_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warga', models.ForeignKey(db_column='warga_id', on_delete=django.db.models.deletion.PROTECT, related_name='pengaduan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pengaduan',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['warga'], name='idx_pengaduan_warga'), models.Index(fields=['status'], name='idx_pengaduan_status'), models.Index(fields=['kategori'], name='idx_pengaduan_kategori'), models.Index(fields=['created_at'], name='idx_pengaduan_created_at')],
            },
        ),
    ]
