# Generated by Django 5.2.15 on 2026-06-13 18:45

import django.db.models.deletion
import pengumuman.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('kategori', models.CharField(choices=[('penting', 'Penting'), ('acara', 'Acara'), ('info', 'Informasi'), ('keamanan', 'Keamanan'), ('lainnya', 'Lainnya')], default='info', max_length=20)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to=pengumuman.models.gambar_upload_path)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Jadwal publikasi. Kosong = segera dipublikasikan.', null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pengumuman_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pengumuman',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kategori'], name='idx_pengumuman_kategori'), models.Index(fields=['is_published'], name='idx_pengumuman_published'), models.Index(fields=['scheduled_at'], name='idx_pengumuman_scheduled'), models.Index(fields=['created_by'], name='idx_pengumuman_created_by')],
            },
        ),
    ]
