# Generated by Django 5.2.15 on 2026-06-13 18:54

import pengumuman.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengumuman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengumuman',
            name='gambar',
            field=models.FileField(blank=True, null=True, upload_to=pengumuman.models.gambar_upload_path),
        ),
    ]
