# Generated by Django 5.2.15 on 2026-06-14 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('isi', models.TextField()),
                ('kategori', models.CharField(choices=[('keamanan', 'Keamanan'), ('kebersihan', 'Kebersihan'), ('acara', 'Acara'), ('usul', 'Usul'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pinned', 'Pinned'), ('locked', 'Locked')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'threads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isi', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forum_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.comment')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.thread')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forum.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'thread_votes',
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['kategori'], name='idx_threads_kategori'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['status'], name='idx_threads_status'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['created_by'], name='idx_threads_created_by'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['thread'], name='idx_comments_thread'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='idx_comments_parent'),
        ),
        migrations.AddIndex(
            model_name='threadvote',
            index=models.Index(fields=['thread'], name='idx_thread_votes_thread'),
        ),
        migrations.AlterUniqueTogether(
            name='threadvote',
            unique_together={('thread', 'user')},
        ),
    ]
