"""Production settings — lihat docs/08-CODING-STANDART.md §3.6 Settings Security."""

from .base import *  # noqa: F401,F403
from .base import env

DEBUG = False

# Security middleware — lihat docs/11-SECURITY.md
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS")
