# Generated by Django 5.2.15 on 2026-06-13 18:22

import django.core.validators
import django.db.models.deletion
import keuangan.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_wargaprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriTransaksi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('tipe', models.CharField(choices=[('pemasukan', 'Pemasukan'), ('pengeluaran', 'Pengeluaran')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kategori_transaksi',
                'ordering': ['tipe', 'nama'],
                'indexes': [models.Index(fields=['tipe'], name='idx_kategori_tipe')],
            },
        ),
        migrations.CreateModel(
            name='IuranWarga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bulan', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('tahun', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('lunas', 'Lunas'), ('ditolak', 'Ditolak')], default='pending', max_length=20)),
                ('bukti_transfer', models.FileField(blank=True, null=True, upload_to=keuangan.models.bukti_upload_path)),
                ('keterangan', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iuran_dikonfirmasi', to=settings.AUTH_USER_MODEL)),
                ('warga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iuran_set', to='accounts.wargaprofile')),
            ],
            options={
                'db_table': 'iuran_warga',
                'ordering': ['-tahun', '-bulan'],
                'indexes': [models.Index(fields=['warga'], name='idx_iuran_warga'), models.Index(fields=['tahun', 'bulan'], name='idx_iuran_periode'), models.Index(fields=['status'], name='idx_iuran_status')],
                'unique_together': {('warga', 'bulan', 'tahun')},
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('keterangan', models.TextField(blank=True, default='')),
                ('tanggal', models.DateField()),
                ('tipe', models.CharField(choices=[('pemasukan', 'Pemasukan'), ('pengeluaran', 'Pengeluaran')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi_dikonfirmasi', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaksi_dibuat', to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaksi_set', to='keuangan.kategoritransaksi')),
            ],
            options={
                'db_table': 'transaksi',
                'ordering': ['-tanggal', '-created_at'],
                'indexes': [models.Index(fields=['tipe'], name='idx_transaksi_tipe'), models.Index(fields=['tanggal'], name='idx_transaksi_tanggal'), models.Index(fields=['status'], name='idx_transaksi_status'), models.Index(fields=['created_by'], name='idx_transaksi_created_by')],
            },
        ),
    ]
