# Generated by Django 5.2.15 on 2026-06-16 05:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


DEFAULT_JENIS = [
    {
        "id": "00000000-0000-4000-8000-000000000001",
        "nama": "Iuran Wajib",
        "slug": "wajib",
        "tipe": "wajib",
        "unit": "per_kk",
        "nominal": 50000,
        "keterangan": "Iuran bulanan wajib setiap kepala keluarga",
        "urutan": 1,
    },
    {
        "id": "00000000-0000-4000-8000-000000000002",
        "nama": "Iuran Kebersihan",
        "slug": "kebersihan",
        "tipe": "opsional",
        "unit": "per_kk",
        "nominal": 20000,
        "keterangan": "Iuran kebersihan lingkungan (opsional)",
        "urutan": 2,
    },
    {
        "id": "00000000-0000-4000-8000-000000000003",
        "nama": "Iuran Jaga Malam",
        "slug": "jaga_malam",
        "tipe": "opsional",
        "unit": "per_kk",
        "nominal": 30000,
        "keterangan": "Iuran keamanan/jaga malam (opsional)",
        "urutan": 3,
    },
]


def seed_jenis_iuran(apps, schema_editor):
    JenisIuran = apps.get_model("keuangan", "JenisIuran")
    for jenis in DEFAULT_JENIS:
        JenisIuran.objects.get_or_create(slug=jenis["slug"], defaults=jenis)


def migrate_existing_iuran(apps, schema_editor):
    """Pindahkan semua IuranWarga lama ke jenis 'wajib'."""
    JenisIuran = apps.get_model("keuangan", "JenisIuran")
    IuranWarga = apps.get_model("keuangan", "IuranWarga")
    try:
        jenis_wajib = JenisIuran.objects.get(slug="wajib")
        IuranWarga.objects.filter(jenis__isnull=True).update(jenis=jenis_wajib)
    except JenisIuran.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_ketua_rt_role'),
        ('keuangan', '0003_pengaturan_saldo_awal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengaturaniuran',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='JenisIuran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('tipe', models.CharField(choices=[('wajib', 'Wajib'), ('opsional', 'Opsional')], default='wajib', max_length=20)),
                ('unit', models.CharField(choices=[('per_warga', 'Per Orang/Warga'), ('per_kk', 'Per KK')], default='per_warga', max_length=20)),
                ('nominal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('keterangan', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('urutan', models.IntegerField(default=0, help_text='Urutan tampil (kecil = pertama)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jenis_iuran',
                'ordering': ['urutan', 'nama'],
                'indexes': [models.Index(fields=['is_active'], name='idx_jenis_iuran_active')],
            },
        ),
        # Seed 3 default jenis iuran sebelum kolom FK ditambah
        migrations.RunPython(seed_jenis_iuran, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='iuranwarga',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='iuranwarga',
            name='jenis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iuran_set', to='keuangan.jenisiuran'),
        ),
        # Pindahkan data IuranWarga lama ke jenis "wajib"
        migrations.RunPython(migrate_existing_iuran, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='iuranwarga',
            unique_together={('warga', 'jenis', 'bulan', 'tahun')},
        ),
        migrations.AddIndex(
            model_name='iuranwarga',
            index=models.Index(fields=['jenis'], name='idx_iuran_jenis'),
        ),
    ]
