# Generated by Django 5.2.15 on 2026-06-14 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('tanggal', models.DateTimeField()),
                ('lokasi', models.CharField(blank=True, max_length=255, null=True)),
                ('kuota_peserta', models.PositiveIntegerField(blank=True, null=True)),
                ('rsvp_buka_at', models.DateTimeField(blank=True, null=True)),
                ('rsvp_tutup_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kegiatan_created', to=settings.AUTH_USER_MODEL)),
                ('penanggung_jawab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kegiatan_penanggung_jawab', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kegiatan',
                'ordering': ['tanggal'],
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('tidak_hadir', 'Tidak Hadir'), ('masih_ragu', 'Masih Ragu')], default='hadir', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp', to='kegiatan.kegiatan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rsvp',
            },
        ),
        migrations.AddIndex(
            model_name='kegiatan',
            index=models.Index(fields=['tanggal'], name='idx_kegiatan_tanggal'),
        ),
        migrations.AddIndex(
            model_name='kegiatan',
            index=models.Index(fields=['created_by'], name='idx_kegiatan_created_by'),
        ),
        migrations.AddIndex(
            model_name='rsvp',
            index=models.Index(fields=['kegiatan'], name='idx_rsvp_kegiatan'),
        ),
        migrations.AddIndex(
            model_name='rsvp',
            index=models.Index(fields=['user'], name='idx_rsvp_user'),
        ),
        migrations.AlterUniqueTogether(
            name='rsvp',
            unique_together={('kegiatan', 'user')},
        ),
    ]
